import type { Metadata, Viewport } from 'next';
import { Space_Grotesk, JetBrains_Mono } from 'next/font/google';
import { site, socials } from '@/data/site';
import { getActiveTrack } from '@/data/tracks';
import { trackSeo } from '@/data/tracks/seo';
import { MotionProvider } from '@/components/MotionProvider';
import './globals.css';

// The portfolio this deployment serves (PORTFOLIO_TRACK) drives the structured
// data so jobTitle/description match the active track, not a hardcoded general.
const activeTrack = getActiveTrack();
const seo = trackSeo[activeTrack.key];

// Structured data for Google. sameAs lists only real (non-placeholder) profiles.
const personJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Person',
  name: site.name,
  alternateName: site.handle,
  url: site.url,
  email: `mailto:${site.email}`,
  jobTitle: activeTrack.label,
  description: seo.description,
  // TODO(owner): PortalHq (prior role) was removed per "QuickBite is the truth". If it should still
  // appear as prior experience, add it back via an alumniOf / separate Organization entry, not worksFor.
  worksFor: { '@type': 'Organization', name: 'QuickBite' },
  knowsAbout: [
    'Distributed Systems',
    'Fintech Infrastructure',
    'Go',
    'NestJS',
    'Next.js',
    'React Native',
    'TypeScript',
    'Docker',
    'PostgreSQL',
  ],
  sameAs: socials
    .filter((s) => s.href.startsWith('http'))
    .map((s) => s.href),
};

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-space-grotesk',
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-jetbrains-mono',
});

export const viewport: Viewport = {
  themeColor: '#0a0a0f',
  colorScheme: 'dark',
};

export const metadata: Metadata = {
  metadataBase: new URL(site.url),
  // Title/description follow the active track's SEO so meta stays consistent with the page
  // and no stale identity (PortalHq) lingers in one place after being fixed in another.
  title: seo.title,
  description: seo.description,
  keywords: [
    'Faith Popoola',
    'Software Engineer',
    'Backend Engineer',
    'Distributed Systems',
    'Fintech Infrastructure',
    'React Native',
    'NestJS',
    'Go',
    'QuickBite',
  ],
  authors: [{ name: 'Faith Popoola' }],
  creator: 'Faith Popoola',
  alternates: { canonical: '/' },
  // og:image / twitter:image and the favicon are generated by the App-Router
  // file conventions (app/opengraph-image.tsx, app/icon.tsx, app/apple-icon.tsx),
  // which emit real PNGs that social scrapers can render.
  openGraph: {
    type: 'website',
    url: site.url,
    title: seo.title,
    description: seo.description,
    siteName: 'Faith Popoola',
  },
  twitter: {
    card: 'summary_large_image',
    title: seo.title,
    description: seo.description,
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // data-track drives the per-track accent + typography posture (globals.css).
  return (
    <html
      lang="en"
      className={`${spaceGrotesk.variable} ${jetbrainsMono.variable}`}
    >
      <body className="font-sans antialiased" data-track={activeTrack.key}>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(personJsonLd) }}
        />
        <MotionProvider>{children}</MotionProvider>
      </body>
    </html>
  );
}
