import type { Metadata, Viewport } from 'next';
import { Space_Grotesk, JetBrains_Mono } from 'next/font/google';
import { site, socials } from '@/data/site';
import './globals.css';

// Structured data for Google. sameAs lists only real (non-placeholder) profiles.
const personJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Person',
  name: site.name,
  alternateName: site.handle,
  url: site.url,
  email: `mailto:${site.email}`,
  jobTitle: 'Software Engineer',
  description:
    'Full-stack engineer & Frontend Lead @ PortalHq building production fintech and platform systems end-to-end.',
  worksFor: { '@type': 'Organization', name: 'PortalHq' },
  alumniOf: {
    '@type': 'CollegeOrUniversity',
    name: 'Obafemi Awolowo University (OAU)',
  },
  knowsAbout: [
    'Distributed Systems',
    'Fintech Infrastructure',
    'Go',
    'NestJS',
    'Next.js',
    'React Native',
    'TypeScript',
    'Docker',
    'PostgreSQL',
  ],
  sameAs: socials
    .filter((s) => s.href.startsWith('http'))
    .map((s) => s.href),
};

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-space-grotesk',
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-jetbrains-mono',
});

export const viewport: Viewport = {
  themeColor: '#0a0a0f',
  colorScheme: 'dark',
};

export const metadata: Metadata = {
  metadataBase: new URL(site.url),
  title: 'Faith Popoola | Software Engineer',
  description:
    'Faith "XS" Popoola — Full-stack engineer & Frontend Lead @ PortalHq. I build production fintech and platform systems end-to-end: React Native, NestJS, Go, distributed systems.',
  keywords: [
    'Faith Popoola',
    'Software Engineer',
    'Full-stack Engineer',
    'Frontend Lead',
    'React Native',
    'NestJS',
    'Go',
    'Distributed Systems',
    'Fintech',
    'OAU',
  ],
  authors: [{ name: 'Faith Popoola' }],
  creator: 'Faith Popoola',
  alternates: { canonical: '/' },
  // og:image / twitter:image and the favicon are generated by the App-Router
  // file conventions (app/opengraph-image.tsx, app/icon.tsx, app/apple-icon.tsx),
  // which emit real PNGs that social scrapers can render.
  openGraph: {
    type: 'website',
    url: site.url,
    title: 'Faith Popoola | Software Engineer',
    description:
      'Full-stack engineer & Frontend Lead @ PortalHq. Production fintech and platform systems, end-to-end.',
    siteName: 'Faith Popoola',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Faith Popoola | Software Engineer',
    description:
      'Full-stack engineer & Frontend Lead @ PortalHq. Production fintech and platform systems, end-to-end.',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${spaceGrotesk.variable} ${jetbrainsMono.variable}`}
    >
      <body className="font-sans antialiased">
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(personJsonLd) }}
        />
        {children}
      </body>
    </html>
  );
}
